<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\TagRequest;
use App\Models\Field;
use App\Models\Group;

class GroupController extends BaseController {

    protected $modelClass = Group::class;
    protected $title      = 'المجموعات';
    protected $route      = 'groups';


    public function index($query = null)
    {
        $query = Group::withCount('contacts');
        return parent::index($query); // TODO: Change the autogenerated stub
    }

}